---
# tasks file for roles/nginx
- name: Install Nginx on vm2
  apt:
    name: nginx
    state: present
  become: yes

- name: Start and Enable Nginx
  service:
    name: nginx
    state: started
    enabled: yes
